language: php
php:
  - '5.6'
#  - '7.0'
#  - '7.1'
#  - '7.2'
before_script: composer install
script:
  - php ./vendor/bin/phpunit tests\WsServices\GetImageTest
after_success:
  - bash <(curl -s https://codecov.io/bash)