dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly
before_script: composer install
before_install: echo "extension = php_curl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - php ./vendor/bin/phpcs -p -n --standard=PSR2 src
  - php ./vendor/bin/phpunit tests/WsServices/
after_success:
  - bash <(curl -s https://codecov.io/bash)